---
# tasks file for nrser.kube-lego

# see https://github.com/jetstack/kube-lego/tree/master/examples/gce

- name: >-
    Set source and destination paths for the deployment file templates.
  set_fact:
    kube_lego_templates:
    - src: Namespace.yml.j2
      dest: >-
        {{ kube_lego_out }}/Namespace.yml
    
    - src: Ingress.yml.j2
      dest: >-
        {{ kube_lego_out }}/{{ kube_lego_name }}.Ingress.yml
      
    - src: ConfigMap.yml.j2
      dest: >-
        {{ kube_lego_out }}/ConfigMap.yml
    
    - src: Deployment.yml.j2
      dest: >-
        {{ kube_lego_out }}/Deployment.yml

- name: >
    Create out directory `{{ kube_lego_out }}`.
  file:
    dest: >-
      {{ kube_lego_out }}
    state: directory

- name: >-
    Generate deployment files.
  template:
    src: >-
      {{ kube_lego_template.src }}
    dest: >-
      {{ kube_lego_template.dest }}
  with_items: >-
    {{ kube_lego_templates }}
  loop_control:
    loop_var: kube_lego_template

- when: kube_lego_deploy
  name: >-
    Deploy kube-lego.
  with_items: >-
    {{ kube_lego_templates }}
  loop_control:
    loop_var: kube_lego_template
  stream:
    template: >-
      kubectl apply <%= opts %>
    kwds:
      opts:
        filename: >-
          {{ kube_lego_template.dest }}
        force: >-
          {{ kube_lego_force }}

