---
# tasks file for nrser.kube-lego

# see https://github.com/jetstack/kube-lego/tree/master/examples/gce

- set_fact:
    # kube_lego_namespace_dest: "{{ kube_lego_out }}/Namespace.yml"
    kube_lego_ingress_dest: "{{ kube_lego_out }}/{{ kube_lego_name }}.Ingress.yml"
    kube_lego_configmap_dest: "{{ kube_lego_out }}/ConfigMap.yml"

- name: >
    create out directory {{ kube_lego_out }}
  file:
    dest: "{{ kube_lego_out }}"
    state: directory

# - name: >
#     render Namespace template to {{ kube_lego_namespace_dest }}    
#   template:
#     src: Namespace.yml.j2
#     dest: "{{ kube_lego_namespace_dest }}"

- name: >
    render Ingress template to {{ kube_lego_ingress_dest }}    
  template:
    src: Ingress.yml.j2
    dest: "{{ kube_lego_ingress_dest }}"

- name: >
    render ConfigMap template to {{ kube_lego_configmap_dest }}
  template:
    src: ConfigMap.yml.j2
    dest: "{{ kube_lego_configmap_dest }}"

- name: deploy kube-lego
  when: kube_lego_deploy
  command: >
    kubectl apply -f {{ item }}
  with_items:
  - "{{ lookup('resolve', 'kube-lego/examples/gce/lego/00-namespace.yaml') }}"
  - "{{ kube_lego_configmap_dest }}"
  - "{{ kube_lego_ingress_dest }}"
  - "{{ lookup('resolve', 'kube-lego/examples/gce/lego/deployment.yaml') }}"
